Repository uncscode/particula, pull requests merged in 2021-12, with the labels that each got.

#32 add flake8, pylint, and pytest via github action
  .github/workflows/python-package.yml
Labels: enhancement

#49 v0.0.2 (linting stuff, fixing bugs, more layout orgs, etc.)
  .github/workflows/python-package-lint.yml
  .github/workflows/python-package-test.yml
  CONTRIBUTING.md
  README.md
  aerosol_dynamics/__init__.py
  docs/000_beginnings.ipynb
  docs/001_particle.ipynb
  docs/_config.yml
  docs/intro.md
  particula/__init__.py
  particula/aerosol_dynamics/__init__.py
  particula/aerosol_dynamics/environment.py
  particula/aerosol_dynamics/environment_test.py
  particula/aerosol_dynamics/parcel.py
  particula/aerosol_dynamics/parcel_test.py
  particula/aerosol_dynamics/particle.py
  particula/aerosol_dynamics/particle_test.py
  particula/aerosol_dynamics/physical_parameters.py
  requirements.txt
  setup.cfg
Labels: bug

#56 Gorkowski/issue48
  .gitignore
  particula/aerosol_dynamics/parcel.py
  particula/aerosol_dynamics/parcel_test.py
Labels: particlephase

#68 documentation sweep
  .github/CODEOWNERS
  .github/workflows/CODEOWNERS
  .gitignore
  CONTRIBUTING.md
  docs/000_beginnings.ipynb
  docs/_config.yml
  docs/_toc.yml
  docs/contrib_docs.md
  docs/intro.md
Labels: documentation
